UPDATE job_order_view a
SET a.origin_idx = (SELECT origin_idx FROM job_order WHERE job_id = a.job_id),
	a.destination_idx = (SELECT destination_idx FROM job_order WHERE job_id = a.job_id),
	a.tariff_idx = (SELECT tariff_idx FROM job_order WHERE job_id = a.job_id),
	a.client_id = (SELECT client_id FROM job_order WHERE job_id = a.job_id),
	a.office_idx = (SELECT office_idx FROM job_order WHERE job_id = a.job_id),
	a.payment_mode = (SELECT payment_mode FROM job_order WHERE job_id = a.job_id),
	a.pickup_id = (SELECT pickup_id FROM job_order WHERE job_id = a.job_id),
	a.product_idx = (SELECT product_idx FROM job_order WHERE job_id = a.job_id),
    a.payment_mode = (SELECT payment_mode FROM job_order WHERE job_id = a.job_id),
    a.shipment_type = (SELECT shipment_type FROM job_order WHERE job_id = a.job_id)

UPDATE job_order_view a
SET 
	a.payment_name = (SELECT account_name FROM master_payment_account WHERE idx = a.payment_mode AND status_delete = "N"),
	a.product_name = (SELECT product_name FROM master_product WHERE idx = a.product_idx AND status_delete = "N"),
	a.product_code = (SELECT product_code FROM master_product WHERE idx = a.product_idx AND status_delete = "N"),
	a.product_title_idx = (SELECT product_title FROM master_product WHERE idx = a.product_idx AND status_delete = "N"),
	a.pickup_type = (SELECT pickup_type FROM job_order WHERE job_id = a.job_id),
	a.pickup_by = (SELECT pickup_by FROM job_order WHERE job_id = a.job_id),
	a.origin_code = (SELECT location_code FROM master_location WHERE idx = a.origin_idx AND status_delete = "N"),
	a.origin_name = (SELECT location_name FROM master_location WHERE idx = a.origin_idx AND status_delete = "N"),
	a.origin_district = (SELECT district_name FROM master_location WHERE idx = a.origin_idx AND status_delete = "N"),
	a.origin_province = (SELECT province_name FROM master_location WHERE idx = a.origin_idx AND status_delete = "N"),
	a.origin_point = (SELECT origin_point FROM job_order WHERE job_id = a.job_id),
	a.origin_place = (SELECT origin_place FROM job_order WHERE job_id = a.job_id),
	a.org_name = (SELECT org_name FROM job_order WHERE job_id = a.job_id),
	a.origin_region = (SELECT origin_region FROM job_order WHERE job_id = a.job_id),
	a.origin_city = (SELECT origin_city FROM job_order WHERE job_id = a.job_id),
	a.origin_place_spec = (SELECT origin_place_spec FROM job_order WHERE job_id = a.job_id),
	a.origin_postcode = (SELECT origin_postcode FROM job_order WHERE job_id = a.job_id),
	a.origin_pic = (SELECT origin_pic FROM job_order WHERE job_id = a.job_id),
	a.origin_phone = (SELECT origin_phone FROM job_order WHERE job_id = a.job_id),
	a.origin_lat = (SELECT origin_lat FROM job_order WHERE job_id = a.job_id),
	a.origin_lng = (SELECT origin_lng FROM job_order WHERE job_id = a.job_id),
	a.destination_code = (SELECT location_code FROM master_location WHERE idx = a.destination_idx AND status_delete = "N"),
	a.destination_name = (SELECT location_name FROM master_location WHERE idx = a.destination_idx AND status_delete = "N"),
	a.destination_district = (SELECT district_name FROM master_location WHERE idx = a.destination_idx AND status_delete = "N"),
	a.destination_province = (SELECT province_name FROM master_location WHERE idx = a.destination_idx AND status_delete = "N"),
	a.destination_point = (SELECT destination_point FROM job_order WHERE job_id = a.job_id),
	a.destination_place = (SELECT destination_place FROM job_order WHERE job_id = a.job_id),
	a.dest_name = (SELECT dest_name FROM job_order WHERE job_id = a.job_id),
	a.destination_region = (SELECT destination_region FROM job_order WHERE job_id = a.job_id),
	a.destination_city = (SELECT destination_city FROM job_order WHERE job_id = a.job_id),
	a.destination_place_spec = (SELECT destination_place_spec FROM job_order WHERE job_id = a.job_id),
	a.destination_postcode = (SELECT destination_postcode FROM job_order WHERE job_id = a.job_id),
	a.destination_pic = (SELECT destination_pic FROM job_order WHERE job_id = a.job_id),
	a.destination_phone = (SELECT destination_phone FROM job_order WHERE job_id = a.job_id),
	a.destination_lat = (SELECT destination_lat FROM job_order WHERE job_id = a.job_id),
	a.destination_lng = (SELECT destination_lng FROM job_order WHERE job_id = a.job_id)

UPDATE job_order_view a
SET 
	a.value_insurance = (SELECT value_insurance FROM job_order WHERE job_id = a.job_id),
	a.value_insurance_item = (SELECT value_insurance_item FROM job_order WHERE job_id = a.job_id),
	a.value_insurance_premi = (SELECT value_insurance_premi FROM job_order WHERE job_id = a.job_id),
	a.value_packing = (SELECT value_packing FROM job_order WHERE job_id = a.job_id),
	a.value_discount = (SELECT value_discount FROM job_order WHERE job_id = a.job_id),
	a.value_other = (SELECT value_other FROM job_order WHERE job_id = a.job_id),
	a.basic_value = (SELECT basic_value FROM job_order WHERE job_id = a.job_id),
	a.charge_value = (SELECT charge_value FROM job_order WHERE job_id = a.job_id),
	a.distance = (SELECT distance FROM job_order WHERE job_id = a.job_id),
	a.unit_distance = (SELECT unit_distance FROM job_order WHERE job_id = a.job_id),
	a.status_packing = (SELECT status_packing FROM job_order WHERE job_id = a.job_id),
	a.status_insurance = (SELECT status_insurance FROM job_order WHERE job_id = a.job_id),
	a.status_document_back = (SELECT status_document_back FROM job_order WHERE job_id = a.job_id),
	a.modified_on = (SELECT modified_on FROM job_order WHERE job_id = a.job_id),
	a.modified_by = (SELECT modified_by FROM job_order WHERE job_id = a.job_id)

UPDATE job_order_view a
SET 
	a.client_code = (SELECT client_code FROM master_client WHERE client_id = a.client_id),
	a.client_name = (SELECT client_name FROM master_client WHERE client_id = a.client_id),
	a.tariff_based_on = (SELECT based_on_charge_view FROM master_tariff_intercity WHERE idx = a.tariff_idx),
	a.tariff_client_name = (SELECT client_name FROM master_tariff_intercity WHERE idx = a.tariff_idx),
	a.tariff_value = (SELECT tariff_value FROM master_tariff_intercity WHERE idx = a.tariff_idx),
	a.tariff_value_next = (SELECT tariff_value_next FROM master_tariff_intercity WHERE idx = a.tariff_idx),
	a.tariff_min_qty = (SELECT minimum_qty FROM master_tariff_intercity WHERE idx = a.tariff_idx),
	a.status_document_back_name = IF(a.status_document_back = 1, "Ya", "Tidak")